create table Person
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(100) NOT NULL UNIQUE,
    year_birthday int          NOT NULL
);

create table Book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name varchar NOT NULL,
    author    varchar NOT NULL,
    year      int     NOT NULL,
    book_id   int REFERENCES Person (id)
);

insert into Person(name, age)
VALUES ('Ivanov Ivan Ivanovich', 1995);
insert into Person(name, age)
VALUES ('Lebedinskay Elena Aleksandrovna', 1973);
insert into Person(name, age)
VALUES ('Radov Yriy Stanislavovich', 1979);
insert into Person(name, age)
VALUES ('Shunin Aleksandr Yrijovich', 1972);

insert into Book(book_name, author, year, book_id)
VALUES ('BookOne', 'authorOne', 2019, 1);
insert into Book(book_name, author, year, book_id)
VALUES ('BookTwo', 'authorTwo', 2000, 2);
insert into Book(book_name, author, year, book_id)
VALUES ('BookThree', 'authorThree', 1999, 4);
insert into Book(book_name, author, year, book_id)
VALUES ('BookFour', 'authorFour', 2012, 4);

select * from Person;
select * from Book;